master_oauth:
  authorization_endpoint: https://example.com/auth
  token_endpoint: https://example.com/token
  client_id: example
  redirect_uri: http://localhost:3000/oauth/callback
  scopes: [openid, profile]

hosting:
  platform: node
  port: 3000

routing:
  loadBalancer:
    strategy: round_robin
  retry:
    maxRetries: 3
    baseDelayMs: 250
    maxDelayMs: 4000
    backoffFactor: 2
    jitter: full
  circuitBreaker:
    failureThreshold: 5
    successThreshold: 2
    recoveryTimeoutMs: 30000

servers:
  - id: local-a
    type: local
    auth_strategy: bypass_auth
    config: {}
  - id: local-b
    type: local
    auth_strategy: bypass_auth
    config: {}

