hosting:
  platform: node
  port: 3000

master_oauth:
  authorization_endpoint: https://example.com/oauth/authorize
  token_endpoint: https://example.com/oauth/token
  client_id: master-mcp
  redirect_uri: http://localhost:3000/oauth/callback
  scopes: [openid]

servers:
  - id: tools
    type: local
    auth_strategy: bypass_auth
    config:
      port: 3333

